apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-kubernetes-configserver-config
data:
  application.properties: |
    # Add your properties here
    server.port: 8888
    spring.cloud.config.server.git.uri: file:///C:/Users/Arjun.Anappara/ws/spring-boot-config-repo
