apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-kubernetes-configserver
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: spring-cloud-kubernetes-configserver